import './globals.scss'
import type { Metadata } from "next";
import BootstrapClient from "../components/BootstrapClient";
import localFont from 'next/font/local';


export const metadata: Metadata = {
  title: "GoForUmrah - Your umrah partner",
  description: "Generated by create next app",
};
const GeneralSans = localFont({
  src: [
    {
      path: '../assets/font/GeneralSans-Regular.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../assets/font/GeneralSans-Semibold.otf',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../assets/font/GeneralSans-Medium.otf',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../assets/font/GeneralSans-Bold.otf',
      weight: '700',
      style: 'normal',
    },
  ],
})
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">

      <body className={GeneralSans.className}>
        {children}
        <BootstrapClient />
      </body>

    </html>
  );
}
